#!/usr/bin/env python3
"""Decompose imported claims into named holes — the R0 → R2 step.

## Where the terms come from, and why not from a model

A claim is decomposable when its holes can be ENUMERATED. The temptation is to
run prose through something that guesses noun phrases; the result is a list
nobody can audit, in a system whose entire argument is that you should not have
to take its word for anything.

So the terms are read off the AUTHOR'S OWN MARKUP. `code spans` and **emphasis**
in a requirements document are not decoration — they are where the writer said
"this word carries weight", and in Studio's document they resolve to exactly the
domain vocabulary: `sponsor:edit`, `deploy:*`, `public`, **org admin**,
**reseller agreement**. Nothing is inferred. If the author marked nothing, this
tool extracts nothing and says so, which is itself a signal about the claim.

## What it will not do

**Promote a claim it learned nothing about.** A claim with no marked vocabulary
stays where the importer left it. 23 of Studio's 69 are in that position, and
reporting them as decomposed would be inventing the evidence the rung is
supposed to represent.

**Bind a term.** Extraction names a hole; it does not fill one. Binding is a
person confirming a referent against a population, which is the one step in this
pipeline a machine is not qualified for. Every term emitted here is open.

## Rungs are evidence, not intent

au:R2 is "a skeleton with named holes; open holes are enumerable" — precisely
what a claim with extracted terms has. Promotion carries au:promotedBy, because
ladder-integrity.rq refuses a hand-set rung, and that refusal is the point.

Usage:
    python3 tools/import/decompose.py --corpus corpus/studio
"""

import argparse
import pathlib
import re
import sys

# An emphasis span longer than this is a sentence fragment the author bolded for
# stress, not a term. Kept as a count rather than silently dropped — a decomposer
# that quietly discards half its input is indistinguishable from one that found
# nothing.
MAX_TERM_WORDS = 4


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def slug(s: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return s[:60] or "term"


def extract(predicate: str):
    """Yield (surface, source) for every term the author marked."""
    seen = set()
    for m in re.finditer(r"`([^`]+)`", predicate):
        s = m.group(1).strip()
        if s and s.lower() not in seen:
            seen.add(s.lower())
            yield s, "code-span"
    for m in re.finditer(r"\*\*([^*]+)\*\*", predicate):
        s = m.group(1).strip()
        if not s or s.lower() in seen:
            continue
        if len(s.split()) > MAX_TERM_WORDS:
            continue
        seen.add(s.lower())
        yield s, "emphasis"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--corpus", required=True)
    args = ap.parse_args()

    corpus = pathlib.Path(args.corpus) / "corpus.ttl"
    text = corpus.read_text(encoding="utf-8")

    blocks = re.findall(
        r'st:([\w-]+) a rfc:NormativeStatement ;.*?rfc:predicate "(.*?)" ;\s*rdfs:label "([\w-]+)"',
        text,
        re.S,
    )
    if not blocks:
        sys.exit("decompose: parsed no claims — the corpus shape changed")

    lines = ["""# terms.ttl — GENERATED by tools/import/decompose.py. Do not hand-edit.
#
# The named holes each claim depends on, read off the author's own `code spans`
# and **emphasis**. Nothing here is inferred: if the author marked no
# vocabulary, the claim gets no terms and stays where the importer left it.
#
# ⛔ EVERY term is OPEN. Extraction names a hole; it does not fill one. Binding
# a term means a person confirming a referent against a population, which is the
# one step in this pipeline a machine is not qualified for — so no au:boundTo
# appears anywhere in this file, and R3 ("every term resolves") is unreachable
# from here by construction.

@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rfc:  <https://aion.savvi.io/ontology/rfc#> .
@prefix au:   <https://aion.savvi.io/ontology/authoring#> .
@prefix st:   <https://aion.savvi.io/corpus/studio#> .

st:decomposition a au:Proposal ;
    au:proposalId "p:studio-authz-decomposition" ;
    au:surface au:Ingest ;
    au:intent "Extract the terms the author marked, and promote only the claims that have them." ;
    au:verdict au:Admitted .
"""]

    emitted, promoted, skipped = {}, [], 0
    for local, predicate, label in blocks:
        terms = list(extract(predicate))
        if not terms:
            skipped += 1
            continue
        promoted.append((local, label, terms))
        for surface, source in terms:
            tid = f"term-{slug(surface)}"
            if tid not in emitted:
                emitted[tid] = (surface, source)

    for tid, (surface, source) in sorted(emitted.items()):
        lines.append(
            f'\nst:{tid} a au:TermRef ;\n'
            f'    au:surface "{esc(surface)}" ;\n'
            f'    au:termSource "{source}" .'
        )

    for local, label, terms in promoted:
        refs = " , ".join(f"st:term-{slug(s)}" for s, _ in terms)
        lines.append(
            f"""
st:{local}
    au:hasTerm {refs} ;
    au:rung au:R2 ;
    au:promotedBy st:decomposition ;
    au:stalledOn "unbound-terms: {len(terms)} term(s) named and none confirmed — {esc(', '.join(s for s, _ in terms))}" ."""
        )

    out = corpus.parent / "terms.ttl"
    out.write_text("\n".join(lines) + "\n")

    # The import's rung AND stall must be retracted for promoted claims. Leaving
    # either produces a claim asserting two rungs and two blockers at once —
    # which reads as whichever a query matches first, and silently DOUBLES every
    # per-claim row downstream. Caught by the requirements payload going 133 to
    # 179 for a change that added no claims.
    for local, _, _ in promoted:
        text = re.sub(
            rf"(st:{re.escape(local)} a rfc:NormativeStatement ;.*?)\n    au:rung au:R0 ;\n    au:stalledOn \"[^\"]*\" \.",
            r"\1 .",
            text,
            flags=re.S,
        )
    corpus.write_text(text)

    print(f"claims decomposed:  {len(promoted)}")
    print(f"claims untouched:   {skipped}  (author marked no vocabulary — left where they were)")
    print(f"distinct terms:     {len(emitted)}")
    print(f"all terms OPEN:     yes — binding is a person's job")
    return 0


if __name__ == "__main__":
    sys.exit(main())
