package kg.metrics;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

import org.apache.jena.query.Dataset;
import org.apache.jena.query.QueryExecution;
import org.apache.jena.query.QueryExecutionFactory;
import org.apache.jena.query.QueryFactory;
import org.apache.jena.query.QuerySolution;
import org.apache.jena.query.ResultSet;

import kg.Loader;
import kg.lint.KgLint;
import kg.lint.LintCheck;

/**
 * Generate {@code docs/report/quality.md} — a longitudinal quality dashboard
 * extending the existing corpus report with Tier-2 → Tier-3 coverage
 * metrics and a kg_lint heartbeat.
 *
 * Mode of operation:
 *   bazel run //kg/java/metrics:kg_metrics             # write
 *   bazel run //kg/java/metrics:kg_metrics -- --check  # exit 1 on drift
 *
 * Wired into //ci:pr_gates via {@code metrics_sync_test}, so PRs that
 * change the KG also refresh the dashboard.
 */
public final class KgMetrics {

    private static final String RFC_PREFIX = "https://aion.savvi.io/ontology/rfc#";

    public static void main(String[] args) throws Exception {
        boolean checkOnly = false;
        for (String a : args) {
            if ("--check".equals(a)) checkOnly = true;
            else throw new IllegalArgumentException("unknown arg: " + a);
        }

        Path docsRoot = resolveDocsRoot();
        Path kgRoot = docsRoot.getParent().resolve("kg");
        // Authored-only for snapshot (the editorial view).
        Dataset ds = Loader.loadDataset(kgRoot);

        String content = render(ds, kgRoot);
        Path target = docsRoot.resolve("report").resolve("quality.md");

        if (checkOnly) {
            String existing = Files.exists(target) ? Files.readString(target) : "";
            if (!existing.equals(content)) {
                System.err.println("narrative/report/quality.md is out of sync.");
                System.err.println("Run: bazel run //kg/java/metrics:kg_metrics");
                System.exit(1);
            }
            System.out.println("quality.md in sync");
            return;
        }
        Files.createDirectories(target.getParent());
        Files.writeString(target, content, StandardCharsets.UTF_8);
        System.out.println("wrote " + target + " (" + content.length() + " bytes)");
    }

    // -----------------------------------------------------------------------
    // Top-level renderer
    // -----------------------------------------------------------------------

    static String render(Dataset ds, Path kgRoot) throws IOException {
        StringBuilder out = new StringBuilder(8192);
        out.append("# Quality dashboard\n\n");
        out.append("> **Generated by `kg_metrics`.** Tracks the corpus's structural\n");
        out.append("> coverage and the heartbeat of the iterative-quality loop. Updated\n");
        out.append("> on every PR via `//ci:pr_gates`.\n\n");

        renderSnapshot(ds, out);
        renderCoverage(ds, out);
        renderProofTier(ds, out);
        renderNsTierBreakdown(ds, out);
        renderPerRfcProofCoverage(kgRoot, out);
        renderInferred(kgRoot, out);
        renderLintHeartbeat(ds, kgRoot, out);

        return out.toString();
    }

    // -----------------------------------------------------------------------
    // Per-RFC proof coverage — which RFCs are "proven" and how close are
    // the foundational models. Parses Aion/Derivations/Proofs.lean directly:
    // each derivation block is preceded by a `-- RFC-NNNN — ...` comment,
    // and the block is "kernel-verified" iff it contains no `sorry`.
    // -----------------------------------------------------------------------

    /** RFC IDs treated as the framework's foundational models. Their
     *  combined proof coverage drives the "Foundational models proven"
     *  headline metric. */
    private static final List<String> FOUNDATIONAL_RFCS = List.of(
        "RFC-0001", // Module Authoring Format
        "RFC-0006", // Semantic Type Model
        "RFC-0007", // Aion Primitive and Storage Model
        "RFC-0008"  // Aion Language Surface
    );

    private static void renderPerRfcProofCoverage(Path kgRoot, StringBuilder out) throws IOException {
        out.append("## Per-RFC proof coverage\n\n");
        out.append("> For each RFC, the count of `:Derivation`s in the corpus and how\n");
        out.append("> many have a kernel-verified Lean proof. A derivation counts as\n");
        out.append("> proven if it has a non-`sorry` proof in `Proofs.lean` **OR** any\n");
        out.append("> RFC-tagged worked theorem in `Theorems.lean` (which the parser\n");
        out.append("> recognizes by the same `-- RFC-NNNN — ...` header convention).\n");
        out.append("> An RFC is **\"proven\"** when its coverage hits 100%. The 4\n");
        out.append("> *foundational* RFCs (RFC-0001, RFC-0006, RFC-0007, RFC-0008) are\n");
        out.append("> the proof-of-concept target.\n\n");

        Path proofsFile = kgRoot.getParent().resolve("lean/Aion/Derivations/Proofs.lean");
        Path theoremsRoot = kgRoot.getParent().resolve("lean/Aion/Spec");
        Map<String, int[]> stats = parseProofsLean(proofsFile);

        // Add hand-written worked theorems from every Theorems.lean under
        // lean/Aion/Spec/** (the monolith was split into per-area files on
        // 2026-05-30). Each `-- RFC-NNNN ...` block credits one additional
        // kernel-verified proof against the RFC's deferred set. Capped at
        // the deferred count so coverage never exceeds 100% (hand theorems
        // target previously-deferred derivations).
        Map<String, Integer> handProven = new java.util.LinkedHashMap<>();
        try (java.util.stream.Stream<Path> walk = Files.walk(theoremsRoot)) {
            for (Path tf : (Iterable<Path>) walk.filter(Files::isRegularFile)
                                                .filter(p -> p.getFileName().toString().equals("Theorems.lean"))::iterator) {
                Map<String, Integer> per = parseTheoremsLean(tf);
                for (Map.Entry<String, Integer> e : per.entrySet()) {
                    handProven.merge(e.getKey(), e.getValue(), Integer::sum);
                }
            }
        }
        for (Map.Entry<String, Integer> e : handProven.entrySet()) {
            int[] s = stats.computeIfAbsent(e.getKey(), k -> new int[2]);
            int deferred = s[0] - s[1];
            int credit = Math.min(e.getValue(), deferred);
            s[1] += credit;
        }

        // Headline foundational tally first — the number we're sprinting
        // toward in the proof-tier roadmap.
        int foundationalProven = 0;
        for (String rfcId : FOUNDATIONAL_RFCS) {
            int[] s = stats.getOrDefault(rfcId, new int[]{0, 0});
            if (s[0] > 0 && s[0] == s[1]) foundationalProven++;
        }
        out.append("**Foundational models proven:** ").append(foundationalProven)
           .append(" / ").append(FOUNDATIONAL_RFCS.size()).append("\n\n");

        if (stats.isEmpty()) {
            out.append("_(Proofs.lean not found at ").append(proofsFile).append(")_\n\n");
            return;
        }

        out.append("| RFC | Total | Kernel-verified | Coverage | Status |\n");
        out.append("|---|---:|---:|---:|---|\n");

        // Sort: proven first (100% coverage), then by coverage descending,
        // ties broken by total descending. Foundational RFCs are tagged in
        // the Status column regardless of where they sort.
        List<Map.Entry<String, int[]>> rows = new ArrayList<>(stats.entrySet());
        rows.sort(Comparator
            .comparingDouble((Map.Entry<String, int[]> e) -> coverage(e.getValue())).reversed()
            .thenComparingInt((Map.Entry<String, int[]> e) -> -e.getValue()[0])
            .thenComparing(Map.Entry::getKey));

        Set<String> foundational = Set.copyOf(FOUNDATIONAL_RFCS);
        for (Map.Entry<String, int[]> e : rows) {
            String rfc = e.getKey();
            int total = e.getValue()[0];
            int proved = e.getValue()[1];
            String tag;
            if (total > 0 && proved == total) {
                tag = "✅ proven";
            } else if (foundational.contains(rfc)) {
                tag = "_foundational_";
            } else {
                tag = "";
            }
            out.append(String.format("| %s | %d | %d | %.1f%% | %s |%n",
                rfc, total, proved, 100.0 * proved / Math.max(total, 1), tag));
        }
        out.append('\n');
    }

    private static double coverage(int[] s) {
        return s[0] == 0 ? 0.0 : (double) s[1] / s[0];
    }

    /** Parse {@code lean/Aion/Spec/Theorems.lean} for hand-written
     *  worked theorems tagged with `-- RFC-NNNN ...` headers. Returns
     *  per-RFC counts of distinct hand-proven derivations. Each
     *  RFC-tagged comment block in Theorems.lean credits one
     *  previously-deferred Proofs.lean derivation against the same RFC.
     *  Hand theorems use the same comment convention as Proofs.lean
     *  for parser symmetry. */
    private static Map<String, Integer> parseTheoremsLean(Path theoremsFile) throws IOException {
        Map<String, Integer> counts = new TreeMap<>();
        if (!Files.exists(theoremsFile)) return counts;
        for (String line : Files.readAllLines(theoremsFile, StandardCharsets.UTF_8)) {
            if (line.startsWith("-- RFC-")) {
                int end = line.length();
                for (int i = "-- ".length(); i < line.length(); i++) {
                    char c = line.charAt(i);
                    if (c == ' ' || c == '\t') { end = i; break; }
                }
                String rfc = line.substring("-- ".length(), end);
                counts.merge(rfc, 1, Integer::sum);
            }
        }
        return counts;
    }

    /** Parse {@code lean/Aion/Derivations/Proofs.lean} into per-RFC
     *  {total, kernel-verified} counts. A "block" begins at a
     *  {@code -- RFC-NNNN ...} comment and ends just before the next
     *  such comment (or EOF). The block is kernel-verified iff no line
     *  in it contains the substring {@code "sorry"}. */
    private static Map<String, int[]> parseProofsLean(Path proofsFile) throws IOException {
        Map<String, int[]> stats = new TreeMap<>();
        if (!Files.exists(proofsFile)) return stats;
        List<String> lines = Files.readAllLines(proofsFile, StandardCharsets.UTF_8);

        String currentRfc = null;
        boolean blockHasSorry = false;

        for (String line : lines) {
            if (line.startsWith("-- RFC-")) {
                // Close previous block, if any.
                if (currentRfc != null) {
                    int[] stat = stats.computeIfAbsent(currentRfc, k -> new int[2]);
                    stat[0]++;
                    if (!blockHasSorry) stat[1]++;
                }
                // Start new block; extract `RFC-NNNN` (4 digits, possibly more).
                int end = line.length();
                for (int i = "-- ".length(); i < line.length(); i++) {
                    char c = line.charAt(i);
                    if (c == ' ' || c == '\t') { end = i; break; }
                }
                currentRfc = line.substring("-- ".length(), end);
                blockHasSorry = false;
            } else if (currentRfc != null && line.contains("sorry")) {
                blockHasSorry = true;
            }
        }
        // Close final block.
        if (currentRfc != null) {
            int[] stat = stats.computeIfAbsent(currentRfc, k -> new int[2]);
            stat[0]++;
            if (!blockHasSorry) stat[1]++;
        }
        return stats;
    }

    // -----------------------------------------------------------------------
    // Proof tier — axiom and theorem counts, grounding coverage,
    // mechanization coverage. Tracks the symbolic-first audit's progress.
    // -----------------------------------------------------------------------

    private static void renderProofTier(Dataset ds, StringBuilder out) {
        out.append("## Proof tier\n\n");
        out.append("> Tracks the audit's symbolic foundation: axioms accepted, theorems\n");
        out.append("> derived, inference rules cataloged and mechanized. Grounding\n");
        out.append("> coverage climbs as `kg_normalize` (PR-4+) extracts `:derivedVia`\n");
        out.append("> chains from prose. See `kg/turtle/axioms.ttl` and\n");
        out.append("> `kg/turtle/inference-rules.ttl`.\n\n");
        out.append("| Metric | Value |\n|---|---|\n");

        int axioms = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?a) AS ?n) WHERE { ?a a rfc:Axiom }");
        int substantiveAxioms = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?a) AS ?n) WHERE { ?a a rfc:Axiom ; rfc:axiomKind \"substantive\" }");
        int axiomsMechanized = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?a) AS ?n) WHERE { ?a a rfc:Axiom ; rfc:mechanizedAs ?leanName }");
        out.append(row("Axioms total", String.valueOf(axioms)));
        out.append(row("Axioms (substantive)", String.valueOf(substantiveAxioms)));
        out.append(row("Axioms propositionally encoded in Lean", pct(axiomsMechanized, axioms)
            + " _(see [proof-tier roadmap](../proof-tier-roadmap.md))_"));

        int rules = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?r) AS ?n) WHERE { ?r a rfc:InferenceRule }");
        int mechanizedRules = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?r) AS ?n) WHERE { ?r a rfc:InferenceRule ; rfc:mechanizedAs ?t }");
        int rulesWithPatterns = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?r) AS ?n) WHERE { ?r a rfc:InferenceRule ; rfc:premisePattern ?p ; rfc:conclusionPattern ?c }");
        out.append(row("Inference rules (cataloged)", String.valueOf(rules)));
        out.append(row("Inference rules mechanized in Lean", pct(mechanizedRules, rules)));
        out.append(row("Inference rules with SPARQL schema", pct(rulesWithPatterns, rules)));

        // Theorems (propositions with grounding obligations): NormativeStatement
        // for now; extend the union as new proposition classes appear.
        int theoremsTotal = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + ">\n"
            + "SELECT (COUNT(DISTINCT ?t) AS ?n) WHERE {\n"
            + "  { ?t a rfc:Theorem . } UNION { ?t a rfc:NormativeStatement . }\n"
            + "  FILTER NOT EXISTS { ?t rfc:isAxiom true }\n"
            + "}");
        int theoremsGrounded = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + ">\n"
            + "SELECT (COUNT(DISTINCT ?t) AS ?n) WHERE {\n"
            + "  { ?t a rfc:Theorem . } UNION { ?t a rfc:NormativeStatement . }\n"
            + "  FILTER NOT EXISTS { ?t rfc:isAxiom true }\n"
            + "  ?t (rfc:derivedVia/rfc:premise)+ ?ax .\n"
            + "  ?ax rfc:isAxiom true .\n"
            + "}");
        out.append(row("Theorems (NormativeStatement + explicit)", String.valueOf(theoremsTotal)));
        out.append(row("Theorems grounded in axioms", pct(theoremsGrounded, theoremsTotal)
            + " _(climbs as `kg_normalize` extracts `:derivedVia` from prose; see PR-4+)_"));

        out.append('\n');
    }

    // -----------------------------------------------------------------------
    // NS tier breakdown — Structural / Derivational / Implemented.
    //
    // Per the self-application principle in narrative/aion-roadmap.md, the
    // existing "% proven" metric over-counts: many "proven" NSes are
    // *constructed-to-be-true* (definitionally inevitable from the model's
    // shape — Tier-1 Structural) rather than the result of non-trivial
    // theorem-proving (Tier-2 Derivational) or end-to-end runtime
    // verification (Tier-3 Implemented). This panel makes the split honest.
    // -----------------------------------------------------------------------

    private static void renderNsTierBreakdown(Dataset ds, StringBuilder out) {
        out.append("## NS tier breakdown\n\n");
        out.append("> Partitions every `:NormativeStatement` by discharge\n");
        out.append("> tier (`Structural` / `Derivational` / `Implemented`, from\n");
        out.append("> `rdf/ontology/tier.ttl`, emitted from the Lean `Tier`). Absent in\n");
        out.append("> TTL means UNTIERED, not Structural: the Lean default is a\n");
        out.append("> compile-time convenience for records that exist in the schema, and\n");
        out.append("> an unasserted tier is not a claim about the proof. See\n");
        out.append("> [aion-roadmap.md](../aion-roadmap.md) §self-application.\n\n");
        out.append("| Tier | Count | Share |\n|---|---:|---:|\n");

        int total = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?ns) AS ?n) WHERE { ?ns a rfc:NormativeStatement }");
        int structural = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?ns) AS ?n) WHERE { ?ns a rfc:NormativeStatement ; rfc:tier rfc:Structural }");
        int derivational = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?ns) AS ?n) WHERE { ?ns a rfc:NormativeStatement ; rfc:tier rfc:Derivational }");
        int implemented = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?ns) AS ?n) WHERE { ?ns a rfc:NormativeStatement ; rfc:tier rfc:Implemented }");
        // Without this row the panel read 0 / 0 / 0 over every corpus for as
        // long as rfc:tier had no TTL form, and nothing said so.
        int untiered = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?ns) AS ?n) WHERE { ?ns a rfc:NormativeStatement FILTER NOT EXISTS { ?ns rfc:tier ?t } }");

        out.append("| Structural | ").append(structural).append(" | ").append(pct(structural, total)).append(" |\n");
        out.append("| Derivational | ").append(derivational).append(" | ").append(pct(derivational, total)).append(" |\n");
        out.append("| Implemented | ").append(implemented).append(" | ").append(pct(implemented, total)).append(" |\n");
        out.append("| _untiered_ | ").append(untiered).append(" | ").append(pct(untiered, total)).append(" |\n");
        out.append('\n');
        out.append("**Total NSes:** ").append(total).append('\n');
        out.append('\n');
    }

    // -----------------------------------------------------------------------
    // Corpus snapshot — totals
    // -----------------------------------------------------------------------

    private static void renderSnapshot(Dataset ds, StringBuilder out) {
        out.append("## Corpus snapshot\n\n");
        out.append("| Metric | Count |\n|---|---|\n");
        out.append(row("Triples (default graph)", count(ds, "SELECT (COUNT(*) AS ?n) WHERE { ?s ?p ?o }")));
        out.append(row("RFC documents",
            count(ds, "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?d) AS ?n) WHERE { ?d a rfc:Document }")));
        out.append(row("Sections",
            count(ds, "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?s) AS ?n) WHERE { ?s a rfc:Section }")));
        out.append(row("Normative statements",
            count(ds, "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?r) AS ?n) WHERE { ?r a rfc:NormativeStatement }")));
        out.append(row("Defined terms",
            count(ds, "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?t) AS ?n) WHERE { ?t a rfc:Term }")));
        out.append(row("Diagnostics",
            count(ds, "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?d) AS ?n) WHERE { ?d a rfc:Diagnostic }")));
        out.append(row("Cross-RFC dependsOn edges",
            count(ds, "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(*) AS ?n) WHERE { ?a rfc:dependsOn ?b }")));
        out.append('\n');
    }

    // -----------------------------------------------------------------------
    // Coverage — Tier-2 → Tier-3 migration indicators
    // -----------------------------------------------------------------------

    private static void renderCoverage(Dataset ds, StringBuilder out) {
        out.append("## Tier-2 → Tier-3 coverage\n\n");
        out.append("> Each metric below tracks how much of the corpus's normative content has\n");
        out.append("> moved from free-text into structured, queryable form. Higher is better.\n\n");
        out.append("| Metric | Value |\n|---|---|\n");

        int totalTerms = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?t) AS ?n) WHERE { ?t a rfc:Term }");
        int citedTerms = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + ">\n" +
            "PREFIX claim: <https://aion.savvi.io/ontology/claims#>\n" +
            "SELECT (COUNT(DISTINCT ?t) AS ?n) WHERE {\n" +
            "  ?t a rfc:Term ; rfc:name ?name .\n" +
            "  ?c a claim:Claim .\n" +
            "  FILTER EXISTS { ?c ?p ?o . FILTER(isLiteral(?o) && CONTAINS(LCASE(STR(?o)), LCASE(?name))) }\n" +
            "}");
        out.append(row("Terms cited in ≥1 claim", pct(citedTerms, totalTerms)));

        int totalDiag = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(DISTINCT ?d) AS ?n) WHERE { ?d a rfc:Diagnostic }");
        // Diagnostics aren't yet linked to rules; once :emits lands this becomes meaningful.
        // For now we report 0 to give the metric a "starting line" in the timeseries.
        int linkedDiag = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + ">\n" +
            "SELECT (COUNT(DISTINCT ?d) AS ?n) WHERE {\n" +
            "  ?d a rfc:Diagnostic .\n" +
            "  FILTER EXISTS { ?rule rfc:emits ?d }\n" +
            "}");
        out.append(row("Diagnostics linked via `:emits`", pct(linkedDiag, totalDiag)
            + " _(populate via `kg_edit scaffold-rule --emits …` or v2.1 reasoner rules)_"));

        // Cross-RFC reference health — fraction of `:references` that resolve.
        int totalRefs = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(*) AS ?n) WHERE { ?a rfc:references ?b }");
        int resolvingRefs = count(ds,
            "PREFIX rfc: <" + RFC_PREFIX + "> SELECT (COUNT(*) AS ?n) WHERE { ?a rfc:references ?b . ?b a rfc:Document }");
        out.append(row("`:references` resolving to an RFC Document", pct(resolvingRefs, totalRefs)));

        out.append('\n');
    }

    // -----------------------------------------------------------------------
    // Inferred triples — output of kg_reasoner (v2.0+)
    // -----------------------------------------------------------------------

    private static void renderInferred(Path kgRoot, StringBuilder out) {
        out.append("## Inferred triples\n\n");
        out.append("> Output of `kg_reasoner` — derivations from the authored corpus\n");
        out.append("> (OWL-MICRO closure today; rule-based and LLM-gated layers in v2.1+).\n");
        out.append("> Each derived triple carries a `rfc:inferredBy` provenance marker.\n\n");

        Path inferredFile = kgRoot.resolve("inferred").resolve("aion-inferred.ttl");
        if (!Files.isRegularFile(inferredFile)) {
            out.append("_(reasoner has not been run; run `bazel run //kg/java/reasoner:kg_reasoner`)_\n\n");
            return;
        }
        Dataset inferred = ds_loadInferred(kgRoot);
        out.append("| Metric | Count |\n|---|---|\n");
        out.append(row("Inferred triples",
            count(inferred,
                "PREFIX rfco: <" + RFC_PREFIX + "> "
                + "SELECT (COUNT(DISTINCT ?r) AS ?n) WHERE { ?r rfco:inferredBy ?tag }")));
        out.append(row("New transitive `dependsOn` edges",
            count(inferred,
                "PREFIX rfco: <" + RFC_PREFIX + "> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n"
                + "SELECT (COUNT(DISTINCT ?r) AS ?n) WHERE {\n"
                + "  ?r rfco:inferredBy ?tag ; rdf:predicate rfco:dependsOn .\n"
                + "}")));
        out.append(row("New `extendedBy` edges (from `extends` inverse)",
            count(inferred,
                "PREFIX rfco: <" + RFC_PREFIX + "> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n"
                + "SELECT (COUNT(DISTINCT ?r) AS ?n) WHERE {\n"
                + "  ?r rfco:inferredBy ?tag ; rdf:predicate rfco:extendedBy .\n"
                + "}")));
        out.append('\n');
    }

    /** Load just the inferred file as a standalone Dataset for query. */
    private static Dataset ds_loadInferred(Path kgRoot) {
        org.apache.jena.rdf.model.Model m = org.apache.jena.rdf.model.ModelFactory.createDefaultModel();
        Path f = kgRoot.resolve("inferred").resolve("aion-inferred.ttl");
        if (Files.isRegularFile(f)) {
            org.apache.jena.riot.RDFDataMgr.read(m, f.toUri().toString());
        }
        return org.apache.jena.query.DatasetFactory.create(m);
    }

    // -----------------------------------------------------------------------
    // kg_lint heartbeat — current violation counts per check
    // -----------------------------------------------------------------------

    private static void renderLintHeartbeat(Dataset dsAuthored, Path kgRoot, StringBuilder out) throws IOException {
        out.append("## Lint heartbeat\n\n");
        out.append("> Live count of every `kg_lint` check. A check enters at `warning`;\n");
        out.append("> when the count reaches zero it gets promoted to `error` and pinned to\n");
        out.append("> `//ci:pr_gates` (the ratchet — see `kg/lint/`).\n>\n");
        out.append("> Counts here match `kg_lint run`: queries see authored + reasoner-inferred\n");
        out.append("> triples (so the orphan-diagnostic count reflects rule-derived `:emits` links).\n\n");
        out.append("| Check | Severity | Violations |\n|---|---|---|\n");
        // Each check uses its declared dataset (authored or inferred-aware)
        // matching `kg_lint run`. Counts are uncapped totals so the
        // dashboard reflects real progress even when row displays cap at 100.
        Dataset dsInferred = Loader.loadDatasetWithInferred(kgRoot);
        List<LintCheck> checks = KgLint.loadChecks(kgRoot.resolve("lint"));
        for (LintCheck c : checks) {
            Dataset ds = c.inferred ? dsInferred : dsAuthored;
            int n = c.runWithTotal(ds).total;
            String row = String.format(
                "| `%s` | %s | %s |\n",
                c.name,
                c.severity.name().toLowerCase(),
                n == 0 ? "✓ 0" : (c.severity == LintCheck.Severity.ERROR ? "✗ " + n : "! " + n));
            out.append(row);
        }
        long warnTotal = 0, errTotal = 0;
        List<String> ready = new ArrayList<>();
        for (LintCheck c : checks) {
            Dataset checkDs = c.inferred ? dsInferred : dsAuthored;
            int total = c.runWithTotal(checkDs).total;
            if (c.severity == LintCheck.Severity.WARNING) warnTotal += total;
            if (c.severity == LintCheck.Severity.ERROR)   errTotal  += total;
            if (c.severity == LintCheck.Severity.WARNING && total == 0) ready.add(c.name);
        }
        out.append('\n');
        out.append("**Totals:** ").append(warnTotal).append(" warning row(s), ")
           .append(errTotal).append(" error row(s).\n\n");
        out.append("Promotion candidates (warning checks at zero violations): ");
        out.append(ready.isEmpty() ? "_(none yet)_" : String.join(", ", ready)).append("\n");
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private static int count(Dataset ds, String sparql) {
        try (QueryExecution exec = QueryExecutionFactory.create(QueryFactory.create(sparql), ds)) {
            ResultSet rs = exec.execSelect();
            if (!rs.hasNext()) return 0;
            QuerySolution s = rs.next();
            // Single-column SELECT — read whichever variable exists.
            String v = rs.getResultVars().get(0);
            return s.getLiteral(v).getInt();
        }
    }

    private static String row(String label, Object value) {
        return "| " + label + " | " + value + " |\n";
    }

    private static String pct(int part, int total) {
        if (total == 0) return part + " / 0 (n/a)";
        double p = 100.0 * part / total;
        return String.format("%d / %d (%.1f%%)", part, total, p);
    }

    private static Path resolveDocsRoot() {
        String testSrcDir = System.getenv("TEST_SRCDIR");
        String testWorkspace = System.getenv("TEST_WORKSPACE");
        if (testSrcDir != null && testWorkspace != null) {
            Path p = Paths.get(testSrcDir, testWorkspace, "narrative");
            if (Files.isDirectory(p)) return p;
        }
        String workspace = System.getenv("BUILD_WORKSPACE_DIRECTORY");
        if (workspace != null) {
            Path p = Paths.get(workspace, "narrative");
            if (Files.isDirectory(p)) return p;
        }
        Path cwd = Paths.get("narrative");
        if (Files.isDirectory(cwd)) return cwd;
        throw new IllegalStateException("could not locate narrative/ directory");
    }
}
