-- GENERATED by db/bundle.mjs — do not edit. Re-run the generator.
--
-- Every migration, in order, plus the ledger rows that record them as
-- applied. Paste into the Neon SQL editor as the OWNER role.
--
-- Safe to run once. Running it twice fails on objects that already exist,
-- which is the honest outcome — check the ledger rather than re-running:
--     SELECT filename, applied_at FROM spec.schema_migration ORDER BY filename;

BEGIN;

CREATE SCHEMA IF NOT EXISTS spec;
CREATE TABLE IF NOT EXISTS spec.schema_migration (
    filename   text PRIMARY KEY,
    sha256     text NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

-- ────────────────────────────────────────────────────────────────────────
-- 0001_schema.sql
-- ────────────────────────────────────────────────────────────────────────
-- The two append-only logs, as tables.
--
-- On disk these were JSONL files appended under an in-process Mutex
-- (services/spec/src/proposal.rs:750-811). Serverless has no filesystem to
-- append to and no single process to hold the lock, so they move here — but the
-- shape does not change, because `tools/proposals/materialize.py` still reads
-- JSONL and promotion is what puts a judgement in front of the gates.
--
-- ⛔ TWO LOGS, NOT ONE. A proposal is a person's JUDGEMENT — what a word means,
-- what a requirement should say. An evaluation is a MEASUREMENT: a project ran a
-- query in its own environment and reported a count. Nobody is asked to agree
-- with a measurement. Replaying both from one table would make "who decided
-- this" and "what did it measure" the same question.

CREATE SCHEMA IF NOT EXISTS spec;

-- One character class, because it is the same hazard in three places.
--
-- Python's str.splitlines() splits on all of these; JSON does not, and
-- serde_json emits U+2028/U+2029/U+0085 RAW inside a string rather than
-- escaping them. A proposal carrying a LINE SEPARATOR — pasting from a PDF is
-- the usual way — therefore became two fragments in materialize.py, neither of
-- which parsed, and both were skipped silently: the record stayed in the log,
-- never promoted, and read as "pending, not yet adopted" in the console forever.
--
-- That reader is fixed (it splits on \n now). This domain is the belt: a line
-- that cannot round-trip through a line-oriented file must not enter a log whose
-- whole purpose is to be exported to one.
--
-- ⚠ Spelled with escapes, never literal characters: these are invisible, so a
-- source line containing them literally is a line nobody can review.
CREATE DOMAIN spec.log_line AS text
  CONSTRAINT is_exactly_one_line
  CHECK (VALUE !~ E'[\n\r\u000B\u000C\u001C\u001D\u001E\u0085\u2028\u2029]');

CREATE TABLE spec.proposal_log (
    -- The handle handed back to the caller. Replaces the JSONL byte offset,
    -- which has no meaning in a table; inventing one would be a fabricated
    -- address, and a fabricated address is strictly worse than an absent one.
    --
    -- GENERATED ALWAYS AS IDENTITY, not serial: an identity column needs no
    -- USAGE grant on its sequence, and a role holding USAGE could call setval()
    -- and make a future seq collide with a past one.
    --
    -- ⚠ `seq` IS ORDERED, NOT CONTIGUOUS. Sequences are not transactional, so a
    -- refused INSERT still consumes a value — a rejected vacuous pass leaves a
    -- gap. Measured: three refusals between two accepted rows numbered them 1 and
    -- 5. A gap is therefore evidence that the door did its job, NOT evidence that
    -- a record was removed. Nothing may infer deletion from a missing seq; the
    -- append-only guarantee lives in the triggers and the grants, not in the
    -- numbering.
    seq          bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    -- clock_timestamp(), not now(): now() is transaction start and would be
    -- identical for two rows written in one transaction, which is a lie about
    -- order. Ordering is seq's job regardless; this is for humans.
    written_at   timestamptz NOT NULL DEFAULT clock_timestamp(),

    -- THE LOG LINE, verbatim — byte-identical to what ProposalLog::append would
    -- have written. Export is then `SELECT line ... ORDER BY seq`, with no
    -- re-serialization step that could reorder keys.
    line         spec.log_line NOT NULL,

    -- Derived from the line, for querying. The CHECK makes them unable to lie.
    parent       text NOT NULL,
    author       text NOT NULL,
    author_email text NOT NULL,
    surface      text NOT NULL,
    -- ⛔ Opaque. `canonical` is the canonical JSON of the proposal body AS A
    -- STRING, and it is the pre-image of a content address. jsonb would sort
    -- keys by length-then-bytes rather than lexicographically, collapse
    -- duplicates, and normalize numbers through numeric — so re-emitting from
    -- jsonb yields DIFFERENT bytes for the same proposal. canonical_json exists
    -- (proposal.rs:700-703) precisely so key order cannot depend on a build
    -- detail; storing jsonb would reintroduce that hazard at the storage layer.
    canonical    text NOT NULL,

    CONSTRAINT decomposition_matches_the_line CHECK (
        line::jsonb->>'parent'       IS NOT DISTINCT FROM parent       AND
        line::jsonb->>'author'       IS NOT DISTINCT FROM author       AND
        line::jsonb->>'author_email' IS NOT DISTINCT FROM author_email AND
        line::jsonb->>'surface'      IS NOT DISTINCT FROM surface      AND
        line::jsonb->>'canonical'    IS NOT DISTINCT FROM canonical
    ),
    -- ⑤ Nothing is attributed to nobody. http.rs:420-428 refuses a write with no
    -- principal; this is the same refusal at the one layer a hand-written INSERT
    -- cannot route around.
    CONSTRAINT author_is_named CHECK (length(btrim(author)) > 0),
    -- Every write names the read point its author was looking at. There is no
    -- default: a proposal made against a corpus you were not seeing is a
    -- different proposal.
    CONSTRAINT parent_is_named CHECK (length(btrim(parent)) > 0),
    CONSTRAINT surface_is_known CHECK (surface IN ('Meridian', 'Chat', 'Ingest', 'Agent'))
);

CREATE TABLE spec.evaluation_log (
    seq          bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    written_at   timestamptz NOT NULL DEFAULT clock_timestamp(),
    line         spec.log_line NOT NULL,

    claim             text   NOT NULL,
    project           text   NOT NULL DEFAULT '',
    implementation    text   NOT NULL,
    outcome           text   NOT NULL,
    -- NULL is meaningful and is NOT zero: NULL is "nothing ran", zero is "it ran
    -- and examined nothing". Collapsing them is how a requirement ends up
    -- looking guarded.
    population        bigint,
    query_fingerprint text   NOT NULL DEFAULT '',
    -- The email here, the sub in proposal_log. Deliberately different fields:
    -- overlay.rs:94-100 prefers author_email and falls back to author.
    author            text   NOT NULL,
    detail            text   NOT NULL DEFAULT '',

    CONSTRAINT decomposition_matches_the_line CHECK (
        line::jsonb->>'claim'          IS NOT DISTINCT FROM claim          AND
        line::jsonb->>'implementation' IS NOT DISTINCT FROM implementation AND
        line::jsonb->>'outcome'        IS NOT DISTINCT FROM outcome        AND
        line::jsonb->>'author'         IS NOT DISTINCT FROM author         AND
        (line::jsonb->'population' = 'null'::jsonb) IS NOT DISTINCT FROM (population IS NULL)
    ),
    CONSTRAINT claim_is_named          CHECK (length(btrim(claim)) > 0),
    -- The same claim can pass in one product and be ungroundable in another, and
    -- an unattributed count cannot tell you which.
    CONSTRAINT implementation_is_named CHECK (length(btrim(implementation)) > 0),
    CONSTRAINT author_is_named         CHECK (length(btrim(author)) > 0),
    -- The vocabulary is closed. There is deliberately no Unknown.
    CONSTRAINT outcome_is_an_au_outcome CHECK (
        outcome IN ('Passes', 'Fails', 'Examined', 'Vacuous', 'CannotBeGrounded')),
    CONSTRAINT population_is_not_negative CHECK (population IS NULL OR population >= 0),

    -- ⛔ ③ ZERO IS AN EXCEPTION, NEVER A PASS — the fourth independent refusal,
    -- and the only one that survives a hand-written INSERT.
    --
    -- The door refuses it (console/lib/evaluation.ts, services/spec/src/
    -- evaluation.rs:102-113). materialize.py drops it rather than promoting it.
    -- vacuous-invariant.rq fails the build for any TTL carrying it. All three are
    -- reachable only through a code path somebody chose to run. This one is the
    -- table itself.
    --
    -- `Examined` is in the refused set on purpose: its whole content is "there
    -- were records to look at", and over zero there were not. An Examined over
    -- zero is the same lie in a quieter voice.
    CONSTRAINT zero_is_an_exception_never_a_pass CHECK (
        outcome NOT IN ('Passes', 'Fails', 'Examined')
        OR (population IS NOT NULL AND population > 0))
);

-- ⚠ Deliberately NO unique constraint on `line`. Binding a term to the same
-- reading twice is a fact, not a duplicate, and "later wins" depends on the
-- second record existing. Debounce in the client; never in the schema.

CREATE INDEX proposal_log_parent    ON spec.proposal_log (parent);
CREATE INDEX evaluation_log_claim   ON spec.evaluation_log (claim, implementation);

INSERT INTO spec.schema_migration (filename, sha256) VALUES ('0001_schema.sql', 'c620f46f72e9d9ce07e98886ba449406c5125e219dc5f9c0b91200210808e9a4');

-- ────────────────────────────────────────────────────────────────────────
-- 0002_append_only.sql
-- ────────────────────────────────────────────────────────────────────────
-- Append-only, enforced by the database rather than by convention.
--
-- ② A proposal is not the corpus. The log keeps everything forever — that is the
-- property the whole overlay rests on, because `pending` means "differs from the
-- corpus", never "is in the log". A record that could be edited or removed would
-- make adoption unanswerable: you could no longer tell "this was decided and
-- promoted" from "this was decided, promoted, and then quietly unwritten".
--
-- Correction is another record. Later wins.

CREATE OR REPLACE FUNCTION spec.refuse_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'the log is append-only: % on %.% is refused',
        TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME
      USING ERRCODE = '0A000',
            HINT = 'the record stays. Correct it with another record — later wins. '
                   'pending means "differs from the corpus", never "is in the log".';
END $$;

-- ⛔ A TRIGGER THAT RAISES, NEVER A RULE THAT SWALLOWS.
--
-- `CREATE RULE ... DO INSTEAD NOTHING` is the usual recipe and it is the
-- dishonest one: the UPDATE *succeeds*, affecting zero rows, and the caller
-- believes it worked. That is the same family of error as reporting a pass over
-- an empty population — an operation that examined nothing, reported success.
-- A raised exception is the honest refusal.
--
-- ⚠ FOR EACH STATEMENT, not FOR EACH ROW. A statement-level BEFORE trigger fires
-- even when zero rows match, so `DELETE FROM spec.proposal_log WHERE false` is
-- refused too. The INTENT is refused, not merely the rows.
CREATE TRIGGER refuse_update   BEFORE UPDATE   ON spec.proposal_log
  FOR EACH STATEMENT EXECUTE FUNCTION spec.refuse_mutation();
CREATE TRIGGER refuse_delete   BEFORE DELETE   ON spec.proposal_log
  FOR EACH STATEMENT EXECUTE FUNCTION spec.refuse_mutation();
CREATE TRIGGER refuse_truncate BEFORE TRUNCATE ON spec.proposal_log
  FOR EACH STATEMENT EXECUTE FUNCTION spec.refuse_mutation();

CREATE TRIGGER refuse_update   BEFORE UPDATE   ON spec.evaluation_log
  FOR EACH STATEMENT EXECUTE FUNCTION spec.refuse_mutation();
CREATE TRIGGER refuse_delete   BEFORE DELETE   ON spec.evaluation_log
  FOR EACH STATEMENT EXECUTE FUNCTION spec.refuse_mutation();
CREATE TRIGGER refuse_truncate BEFORE TRUNCATE ON spec.evaluation_log
  FOR EACH STATEMENT EXECUTE FUNCTION spec.refuse_mutation();

-- The append primitives.
--
-- ⛔ The advisory lock is `ProposalLog::append`'s in-process Mutex
-- (proposal.rs:797), relocated to where the log now lives.
--
-- It matters more here than it did there. `GENERATED AS IDENTITY` allocates seq
-- BEFORE commit, so two serverless invocations can take 41 and 42 and commit in
-- the other order. A replay landing in between would see 42, and then 41 — the
-- EARLIER proposal — would arrive and win on the next replay. "Later wins" would
-- depend on who fsynced first, which is not a property of the judgement anybody
-- made. One lock, on a write path that runs at human rate.
CREATE OR REPLACE FUNCTION spec.append_proposal(
    p_line spec.log_line, p_parent text, p_author text,
    p_author_email text, p_surface text, p_canonical text)
RETURNS TABLE (seq bigint, written_at timestamptz)
LANGUAGE plpgsql SECURITY INVOKER AS $$
BEGIN
    PERFORM pg_advisory_xact_lock(hashtext('spec.proposal_log'));
    RETURN QUERY
        INSERT INTO spec.proposal_log
            (line, parent, author, author_email, surface, canonical)
        VALUES (p_line, p_parent, p_author, p_author_email, p_surface, p_canonical)
        RETURNING spec.proposal_log.seq, spec.proposal_log.written_at;
END $$;

CREATE OR REPLACE FUNCTION spec.append_evaluation(
    p_line spec.log_line, p_claim text, p_project text, p_implementation text,
    p_outcome text, p_population bigint, p_query_fingerprint text,
    p_author text, p_detail text)
RETURNS TABLE (seq bigint, written_at timestamptz)
LANGUAGE plpgsql SECURITY INVOKER AS $$
BEGIN
    PERFORM pg_advisory_xact_lock(hashtext('spec.evaluation_log'));
    RETURN QUERY
        INSERT INTO spec.evaluation_log
            (line, claim, project, implementation, outcome, population,
             query_fingerprint, author, detail)
        VALUES (p_line, p_claim, p_project, p_implementation, p_outcome, p_population,
                p_query_fingerprint, p_author, p_detail)
        RETURNING spec.evaluation_log.seq, spec.evaluation_log.written_at;
END $$;

INSERT INTO spec.schema_migration (filename, sha256) VALUES ('0002_append_only.sql', 'f90015b790e1abae616dc43cade9857507143ebc3b02538618921785a7c417de');

-- ────────────────────────────────────────────────────────────────────────
-- 0003_grants.sql
-- ────────────────────────────────────────────────────────────────────────
-- Three roles, because the web tier must not be able to erase the log.
--
-- The triggers in 0002 refuse UPDATE and DELETE, but a role that can
-- `ALTER TABLE ... DISABLE TRIGGER` can undo that. So the console never connects
-- as a role that could.

-- ⚠ ON NEON, CREATE THESE WITH SQL — never in the Neon console.
--
-- A role created in the Neon console is granted `neon_superuser`. A role created
-- with SQL is not. That difference is the whole privilege separation here: a
-- `neon_superuser` member can reach table ownership, and an owner can
-- `ALTER TABLE ... DISABLE TRIGGER` and then delete. Creating the app role in the
-- console would hand the web tier exactly the power 0002 exists to deny it.
--
-- The cost is that these roles do not appear in the Neon console's UI and you
-- build their connection strings by hand. That is the correct trade.
--
-- Idempotent, because a migration that half-applied and then refuses to be
-- retried is a worse failure than one that can be run twice.
DO $$ BEGIN
    -- owns the schema; migrations only, held by CI or a laptop
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'spec_owner') THEN
        CREATE ROLE spec_owner NOLOGIN;
    END IF;
    -- the app connects as this: INSERT + SELECT, nothing else
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'spec_app') THEN
        CREATE ROLE spec_app LOGIN;
    END IF;
    -- the promotion workflow: SELECT only
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'spec_export') THEN
        CREATE ROLE spec_export LOGIN;
    END IF;
END $$;

-- ⛔ NO PASSWORDS HERE, deliberately. A credential in a migration is a credential
-- in git, in the ledger's sha256, and in every clone. Set them once, separately:
--
--     ALTER ROLE spec_app    WITH PASSWORD '...';
--     ALTER ROLE spec_export WITH PASSWORD '...';
--
-- Until then both roles exist and neither can connect, which is the safe state.

-- ⚠ PostgreSQL 16+ requires membership in a role WITH SET to hand it ownership,
-- and ADMIN alone is not enough.
--
-- A CREATEROLE role is auto-granted ADMIN on roles it creates, which is why this
-- looks unnecessary and is not: on Neon, `neondb_owner` creates `spec_owner`
-- three lines up and then cannot give it anything —
--
--     ERROR: must be able to SET ROLE "spec_owner"   (42501)
--
-- Measured against Neon (PostgreSQL 17.10), not inferred. It does not reproduce
-- as a local superuser, which is exactly the shape of bug that reaches a
-- deployment: the environment that finds it is the one you cannot test in.
DO $$ BEGIN
    EXECUTE format('GRANT spec_owner TO %I WITH SET TRUE', current_user);
END $$;

ALTER SCHEMA spec                OWNER TO spec_owner;
ALTER TABLE  spec.proposal_log   OWNER TO spec_owner;
ALTER TABLE  spec.evaluation_log OWNER TO spec_owner;

REVOKE ALL ON SCHEMA spec              FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA spec FROM PUBLIC;

GRANT USAGE ON SCHEMA spec TO spec_app, spec_export;

-- ⛔ INSERT and SELECT. Never UPDATE, never DELETE, never TRUNCATE.
--
-- ⚠ TRUNCATE is a SEPARATE privilege and is NOT implied by DELETE. Revoking
-- DELETE and leaving TRUNCATE reachable is the classic mistake here, and it is
-- the one that empties the whole log in a single statement. It is simply never
-- granted below — along with REFERENCES, which would let a foreign key make a
-- record undeletable-but-also-unwritable.
GRANT INSERT, SELECT ON spec.proposal_log, spec.evaluation_log TO spec_app;
GRANT SELECT          ON spec.proposal_log, spec.evaluation_log TO spec_export;

GRANT EXECUTE ON FUNCTION
    spec.append_proposal(spec.log_line, text, text, text, text, text) TO spec_app;
GRANT EXECUTE ON FUNCTION
    spec.append_evaluation(spec.log_line, text, text, text, text, bigint, text, text, text)
    TO spec_app;

-- ⚠ THE RESIDUAL HOLE, STATED PLAINLY.
--
-- Whoever holds spec_owner — or Neon's neon_superuser — can disable the triggers
-- and delete. No arrangement inside Postgres closes that; a database cannot
-- defend against its own owner.
--
-- It is closed OUTSIDE Postgres, by committing the exported JSONL snapshot to
-- git (see console/db/README.md and the promotion workflow). A row can vanish
-- from a table without trace; a line cannot vanish from a reviewed diff. That
-- committed snapshot is the second copy, and it is why the export is part of the
-- design rather than a convenience.

INSERT INTO spec.schema_migration (filename, sha256) VALUES ('0003_grants.sql', '9dd9cb8e0eec53a47fb280116e2428f2bf3b087bd80035e07c826312b377e9cb');

-- ────────────────────────────────────────────────────────────────────────
-- 0004_the_door.sql
-- ────────────────────────────────────────────────────────────────────────
-- The door: a proposal gets a name, and the decision that let it in is recorded.
--
-- Until this migration a proposal had no identity. The console answered
-- `"address": null` with `address_computed_by: "the door, in the build"` beside
-- it, and there was no door in the build — so RFC-002 §5's `Proposal.id` did not
-- exist anywhere, `spec replay <id>` (§12 P1) had nothing to take, and §9.1's
-- equal-citizen gate ("a click and a chat that author the same change produce
-- the same id") was unfalsifiable rather than merely unproven.
--
-- Two columns, both derived from the line, both unable to lie about it.
--
--   address   sha256:<64 hex> over canonicalJson({author, ops, parent}).
--             ⛔ THREE FIELDS. `surface` and `intent` are stored in `canonical`
--             and deliberately excluded from the pre-image: RFC-002 §4.1 has the
--             door take `{parents, ops}` and NOT provenance, so the same change
--             from two surfaces is one proposal with two provenance records.
--             Hashing the stored line would give them different names and
--             quietly invert §9.1.
--   verdict   au:Verdict — what the door decided about the proposal as a whole.
--             Admitted (every op well-formed and in capability) or Queued (some
--             op out of capability; partial admission is normal, §5). Never
--             Rejected: a rejected proposal is not appended at all, so the value
--             cannot occur here — and `console/lib/overlay.ts` and
--             `tools/proposals/materialize.py` both refuse to replay a record
--             that carries it, because a decision nothing downstream honours is
--             decoration.
--
-- ⚠ WHAT THIS VERDICT IS NOT. It is not the gate set. RFC-002 §7.1 counts "every
-- named gate returns zero rows after application" as part of admission, and that
-- is a GROUP BY … HAVING over the post-admission graph — Jena, the whole corpus,
-- the ontology. None of that exists in a serverless function. The gate verdict
-- is the BUILD's, on the promotion PR, where //corpus/... and //rdf/... already
-- run. Two verdicts, neither reported as the other.
--
-- ⚠ NULLABLE, and only for one reason: rows written before this migration have
-- no address and no verdict. They are still nameable — the address is
-- recomputable from `canonical`, which is what tools/proposals/replay.py does —
-- but inventing one here would be writing a derived value as though it had been
-- decided at the time. The paired CHECK below makes "pre-door" a whole state
-- rather than a per-column accident.

ALTER TABLE spec.proposal_log ADD COLUMN address text;
ALTER TABLE spec.proposal_log ADD COLUMN verdict text;

-- The shape, lower-case hex, exactly 64 of them. Mirrors ADDRESS_PATTERN in
-- console/lib/address.ts. `~` is case-sensitive: an upper-case digest is a
-- DIFFERENT string that names the same bytes, and two spellings of one address
-- is the whole reason to pin the spelling.
ALTER TABLE spec.proposal_log ADD CONSTRAINT address_is_a_content_address
    CHECK (address IS NULL OR address ~ '^sha256:[0-9a-f]{64}$');

ALTER TABLE spec.proposal_log ADD CONSTRAINT verdict_is_an_au_verdict
    CHECK (verdict IS NULL OR verdict IN ('Admitted', 'Queued'));

-- Half a door is not a door. Either the record was written by one and carries
-- both, or it predates one and carries neither.
ALTER TABLE spec.proposal_log ADD CONSTRAINT the_door_wrote_both_or_neither
    CHECK ((address IS NULL) = (verdict IS NULL));

-- The same arrangement as decomposition_matches_the_line (0001): the columns are
-- for querying, the line is the record, and a CHECK makes the columns unable to
-- disagree with it. `->>` on a missing key is NULL, so IS NOT DISTINCT FROM is
-- what makes a pre-door row pass rather than an OR chain that would also pass a
-- row whose line said something else.
ALTER TABLE spec.proposal_log ADD CONSTRAINT door_decision_matches_the_line
    CHECK (
        line::jsonb->>'address' IS NOT DISTINCT FROM address AND
        line::jsonb->>'verdict' IS NOT DISTINCT FROM verdict
    );

-- ⚠ NOT UNIQUE, and that is the design.
--
-- Two identical proposals from the same author against the same read point have
-- the same address BY CONSTRUCTION — that is what content-addressing means — and
-- both belong in the log. A unique index would turn "I clicked twice" into a
-- 500, and worse, would turn the second author's independent agreement into an
-- error. Deduplication is a READ-side question (later wins), and 0001 already
-- refuses to make `line` unique for the same reason.
CREATE INDEX proposal_log_address ON spec.proposal_log (address);

-- ── the append primitive, with the door's two outputs ────────────────────────
--
-- CREATE first, DROP second: a different argument list is a different function,
-- so the two coexist for the length of this migration and never for longer. One
-- overload is the invariant — two would let a caller append a record with no
-- address by picking the older signature, which is exactly the hole this closes.
CREATE OR REPLACE FUNCTION spec.append_proposal(
    p_line spec.log_line, p_parent text, p_author text,
    p_author_email text, p_surface text, p_canonical text,
    p_address text, p_verdict text)
RETURNS TABLE (seq bigint, written_at timestamptz)
LANGUAGE plpgsql SECURITY INVOKER AS $$
BEGIN
    -- Refused here as well as by the CHECKs, because the CHECK permits NULL for
    -- the pre-door rows and this path is never one of them. A door that can be
    -- called without deciding anything is not a door.
    IF p_address IS NULL OR p_verdict IS NULL THEN
        RAISE EXCEPTION 'the door decides: append_proposal needs an address and a verdict'
          USING ERRCODE = '22004',
                HINT = 'compute them with console/lib/address.ts; NULL is reserved for '
                       'records written before migration 0004 and cannot be created now.';
    END IF;
    PERFORM pg_advisory_xact_lock(hashtext('spec.proposal_log'));
    RETURN QUERY
        INSERT INTO spec.proposal_log
            (line, parent, author, author_email, surface, canonical, address, verdict)
        VALUES (p_line, p_parent, p_author, p_author_email, p_surface, p_canonical,
                p_address, p_verdict)
        RETURNING spec.proposal_log.seq, spec.proposal_log.written_at;
END $$;

DROP FUNCTION spec.append_proposal(spec.log_line, text, text, text, text, text);

-- DROP took the grant with it.
GRANT EXECUTE ON FUNCTION
    spec.append_proposal(spec.log_line, text, text, text, text, text, text, text) TO spec_app;

-- ── a machine reports, never judges — now in the schema too ──────────────────
--
-- RFC-004a §4. `console/lib/evaluation.ts`, `services/spec/src/evaluation.rs` and
-- `conformance/check_conformance.py` all refuse a `Passes` or a `Fails` from a
-- `machine:` author; #48 landed that and filed the database half as a follow-up
-- because it needed a migration. This is it.
--
-- It is not redundant with the door. It is the same refusal at the one layer a
-- hand-written INSERT cannot route around — the layer that also holds ③ (zero is
-- an exception, never a pass), and for the same reason: an append-only log keeps
-- a bad row forever, so the last place to catch one is the place it lands.
--
-- ⚠ `NOT LIKE` with no ESCAPE clause: the pattern is a literal prefix and a
-- wildcard, and `machine:` contains no `%` or `_` to be confused about.
ALTER TABLE spec.evaluation_log ADD CONSTRAINT a_machine_reports_never_judges
    CHECK (author NOT LIKE 'machine:%' OR outcome NOT IN ('Passes', 'Fails'));

INSERT INTO spec.schema_migration (filename, sha256) VALUES ('0004_the_door.sql', '98258a90a1286ea2479679a106e11be348a192d5ff349bd9a8aa376ef5c9040c');

COMMIT;

-- What you should see afterwards:
--   SELECT tablename, tableowner FROM pg_tables WHERE schemaname = 'spec';
--     proposal_log    | spec_owner
--     evaluation_log  | spec_owner
--
-- Then give the app role a password — it has none, so it cannot connect yet:
--   ALTER ROLE spec_app WITH PASSWORD '<generate one>';
