"""emit_diff_test — generic byte-stable drift gate for a generated artifact.

The test-side counterpart to `//tools:update_artifact.sh`. Pair them as the
emit → update → diff trio for any artifact a build emits and commits:

    load("@spec//tools:diff.bzl", "emit_diff_test")

    # generated by some lean_emit / genrule; committed copy lives in-tree.
    emit_diff_test(
        name = "axioms_ttl_diff_test",
        generated = "//lean:axioms_ttl_generated",
        committed = "//kg/turtle:axioms.ttl",
        update_target = "//lean:update_axioms_ttl",
    )

Fails the build (with a remediation hint naming `update_target`) whenever the
committed copy drifts from the emitter. Runs the `tools.DiffGate` Java tool as a
`java_test`; file locations are resolved through the Bazel runfiles library, so
it works for both main-repo and external-repo inputs with no workspace-name
probing.
"""

load("@rules_java//java:defs.bzl", "java_test")

def emit_diff_test(name, generated, committed, update_target, **kwargs):
    """Byte-compare `generated` against `committed`; fail with a hint otherwise.

    Args:
      name: test target name.
      generated: label of the build-emitted artifact.
      committed: label of the committed copy (source file or filegroup).
      update_target: label string printed in the remediation hint (the target
        that refreshes the committed copy, e.g. an update_artifact.sh wrapper).
      **kwargs: forwarded to the underlying java_test (tags, visibility, …).
    """
    java_test(
        name = name,
        main_class = "tools.DiffGate",
        use_testrunner = False,
        runtime_deps = [Label("//java/tools:diff_gate")],
        args = [
            "$(rlocationpath %s)" % generated,
            "$(rlocationpath %s)" % committed,
            update_target,
        ],
        data = [generated, committed],
        **kwargs
    )
