/-
Spec.Emit.TierVocab — the rfc:Tier vocabulary, emitted from Spec.Corpus.Schema.Tier.

`rfc:tier` had no TTL form: `Tier` was Lean-only, so it was neither queryable
nor drift-checkable (RFC-002 §6.1, §13.3), and a consumer's panel that counted
`rfc:tier rfc:Structural` read 0/0/0 forever. This emits the class, the three
individuals and the property FROM the Lean inductive, so the ontology stays
Lean-defined: //lean:tier_ttl_generated runs `main`, and //lean:tier_ttl_diff_test
pins rdf/ontology/tier.ttl to its output byte for byte.

The exhaustiveness of the emitted vocabulary is a theorem, not a habit: adding a
constructor to `Tier` without extending `allTiers` is a compile error.
-/
import Spec.Corpus.Schema
import Spec.Emit.TtlEmit
-- ⛔ MUST stay. `lean_test` DOES NOT CHECK PROOFS on its own: a `sorry` is a
-- *warning* and `lean` exits 0, so a file proving anything `by sorry` passes a
-- `lean_test` cleanly. Measured on this repo, not inferred. This option turns
-- `declaration uses 'sorry'` into a hard error; //lean:audit_proofs_test asserts
-- every source still carries it, so it cannot be removed one file at a time.
set_option warningAsError true

namespace Spec.Emit.TierVocab

open Spec.Corpus.Schema
open Spec.Emit.TtlEmit

/-- Every `Tier`, in declaration order. -/
def allTiers : List Tier := [.Structural, .Derivational, .Implemented]

/-- `allTiers` is exhaustive. A new constructor makes this fail to compile,
    which is what makes the emitted vocabulary complete rather than remembered. -/
theorem allTiers_complete (t : Tier) : t ∈ allTiers := by
  cases t <;> simp [allTiers]

/-- The local name of the rfc: individual — the constructor's own name. -/
def localName : Tier → String
  | .Structural => "Structural"
  | .Derivational => "Derivational"
  | .Implemented => "Implemented"

/-- The rdfs:comment of each individual, mirroring the docstring on `Tier`. -/
def comment : Tier → String
  | .Structural =>
      "Definitionally true from the model's construction; the Lean theorem exists but its proof is trivial (rfl, intro h; exact h). The conservative floor, and the Lean default for a record that exists in the schema."
  | .Derivational =>
      "Proven by a non-trivial Lean theorem chain from prior axioms, definitions, or earlier theorems. Presupposes R4: a claim must be typed into the Lean corpus schema before a derivational grade means anything, and rdf/lint/authoring/tier-rung-coherence.rq refuses it below R4."
  | .Implemented =>
      "Realized by code that runs in production, with the runtime behavior cross-checked against the spec."

def rfcNs : String := "https://aion.savvi.io/ontology/rfc#"

def header : String :=
  "# tier.ttl — GENERATED by //lean:tier_ttl_generated from Spec.Corpus.Schema.Tier.\n" ++
  "# Do not hand-edit: change lean/Spec/Emit/TierVocab.lean (or the Tier inductive)\n" ++
  "# and run `bazel run //lean:update_tier_ttl`. //lean:tier_ttl_diff_test pins this\n" ++
  "# file to the emitter byte for byte.\n" ++
  "#\n" ++
  "# rfc:tier grades how a NormativeStatement's PROOF is discharged. It is\n" ++
  "# orthogonal to au:rung (how far the claim has been formalized): a claim can be\n" ++
  "# R4 and still Structural; it cannot be Derivational below R4.\n" ++
  "#\n" ++
  "# ⛔ ABSENT MEANS UNTIERED, not Structural. The Lean default is a compile-time\n" ++
  "# convenience for records that exist in the schema; an unasserted TTL tier is\n" ++
  "# not a claim about the proof.\n\n"

def emit : String :=
  header ++
  emitPrefixes [
    ("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#"),
    ("rdfs", "http://www.w3.org/2000/01/rdf-schema#"),
    ("owl", "http://www.w3.org/2002/07/owl#"),
    ("", rfcNs)
  ] ++
  emitQNameSubject ":Tier" [
    ⟨"a", .qname "owl:Class"⟩,
    ⟨"rdfs:label", .str "Proof-discharge tier"⟩,
    ⟨"rdfs:comment", .str "How a NormativeStatement's PROOF is discharged. Orthogonal to au:rung, which grades how far the claim has been formalized: a claim can be fully formalized (R4) and still Structural; it cannot be Derivational below R4 — rdf/lint/authoring/tier-rung-coherence.rq enforces exactly that. Emitted from Spec.Corpus.Schema.Tier by //lean:tier_ttl_generated."⟩
  ] ++ "\n" ++
  String.join (allTiers.map fun t =>
    emitQNameSubject (":" ++ localName t) [
      ⟨"a", .qname ":Tier"⟩,
      ⟨"rdfs:label", .str (localName t)⟩,
      ⟨"rdfs:comment", .str (comment t)⟩
    ] ++ "\n") ++
  emitQNameSubject ":tier" [
    ⟨"a", .qname "owl:ObjectProperty"⟩,
    ⟨"rdfs:domain", .qname ":NormativeStatement"⟩,
    ⟨"rdfs:range", .qname ":Tier"⟩,
    ⟨"rdfs:label", .str "Tier"⟩,
    ⟨"rdfs:comment", .str "Optional. ABSENT MEANS UNTIERED, not Structural: the Lean default is a compile-time convenience for records that exist in the schema, and an unasserted TTL tier is not a claim about the proof. At most one per claim (rdf/ontology/shapes.ttl)."⟩
  ]

end Spec.Emit.TierVocab

-- `lean --run` looks for an unqualified `main`.
def main : IO Unit := IO.print Spec.Emit.TierVocab.emit
