#!/usr/bin/env python3
"""The proposal log → the corpus. The step that makes a proposal real.

## Why this is a separate act, and not something the service does

Writing through the portal appends to an append-only log and the service
overlays that log on what you see, marked PENDING. Nothing is edited in place.
This tool is the promotion: it turns admitted proposals into TTL that lands in
the corpus, which is what the gates run over and what CI checks.

Keeping the two apart is the whole discipline:

  the log      who proposed what, when, against which read point — never rewritten
  the corpus   what the project currently commits to — generated, gated, reviewed

If the service wrote straight to the corpus there would be no reviewable step
between "someone clicked a button" and "the specification changed", and the
gates would be checking a document nobody read.

## What it will not do

**Invent a rung.** A bound term does NOT promote its claims to R3. R3 means
*every* term in a claim resolves; binding one of nine terms in AUTH-31 moves
nothing, and a promotion computed from a partial binding would report progress
that does not exist. Rungs stay where the evidence puts them; this tool records
bindings and lets `ladder-integrity` see what follows.

**Resolve a conflict between two authors.** Later record wins, per the log's
order, and both remain in the log. If that is wrong, the answer is a third
proposal, not an edit here.

Usage:
    python3 tools/proposals/materialize.py \\
        --log /tmp/spec-proposals.jsonl --corpus corpus/studio --project studio
    python3 tools/proposals/materialize.py ... --check    # exit 1 if stale
"""

import argparse
import json
import pathlib
import re
import sys


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def slug(s: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return s[:60] or "term"


def read_log(path: pathlib.Path, project: str):
    """Ops in log order, scoped to one project.

    A record whose canonical body will not parse is SKIPPED. The log is
    append-only and one bad line must not hide the good ones written after it.
    """
    ops = []
    if not path.exists():
        return ops
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            rec = json.loads(line)
            body = json.loads(rec["canonical"])
        except Exception:
            continue
        author = rec.get("author_email") or rec.get("author") or ""
        for op in body.get("ops", []):
            # An op with no project applies everywhere; the portal always sends one.
            if op.get("project") and op["project"] != project:
                continue
            ops.append((op, author, rec.get("parent", "")))
    return ops


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--log", required=True)
    ap.add_argument("--corpus", required=True)
    ap.add_argument("--project", required=True)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the corpus does not already match the log")
    args = ap.parse_args()

    ops = read_log(pathlib.Path(args.log), args.project)

    bound, aligned, retracted_terms = {}, {}, {}
    amended, retracted_ns, asserted = {}, {}, {}
    authors = {}

    for op, author, _parent in ops:
        kind = op.get("op", "")
        if kind == "bindTerm":
            bound[op["term"]] = op.get("definition", "")
        elif kind == "alignTerm":
            aligned[op["term"]] = op.get("aligns_to", "")
        elif kind == "retractTerm":
            retracted_terms[op["term"]] = op.get("reason", "")
        elif kind == "amendNS":
            amended.setdefault(op["subject"], {}).update(
                {k: v for k, v in op.items() if k in ("text", "discipline", "modality") and v}
            )
        elif kind == "retractNS":
            retracted_ns[op["subject"]] = True
        elif kind == "assertNS":
            asserted[op["subject"]] = op
        else:
            continue
        authors[op.get("term") or op.get("subject") or ""] = author

    lines = ["""# proposals.ttl — GENERATED by tools/proposals/materialize.py.
# Do not hand-edit; edit by making another proposal.
#
# Admitted proposals from the authoring log, as corpus statements. Every one
# carries au:promotedBy so ladder-integrity can see that a person — named here —
# is responsible for it, not the importer.
#
# ⛔ A bound term does NOT promote its claims. R3 means every term in a claim
# resolves; binding one of AUTH-31's nine moves nothing. Rungs stay where the
# evidence puts them.

@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rfc:  <https://aion.savvi.io/ontology/rfc#> .
@prefix au:   <https://aion.savvi.io/ontology/authoring#> .
@prefix st:   <https://aion.savvi.io/corpus/PROJECT#> .

st:authoring a au:Proposal ;
    au:proposalId "p:PROJECT-authoring-log" ;
    au:surface au:Meridian ;
    au:intent "Bindings, alignments and amendments made by people in the console." ;
    au:verdict au:Admitted .
""".replace("PROJECT", args.project)]

    for term, definition in sorted(bound.items()):
        lines.append(
            f'\nst:term-{slug(term)}\n'
            f'    au:boundTo "{esc(definition)}" ;\n'
            f'    au:promotedBy st:authoring ;\n'
            f'    rdfs:comment "bound by {esc(authors.get(term, ""))}" .'
        )
    for term, other in sorted(aligned.items()):
        lines.append(
            f'\nst:term-{slug(term)}\n'
            f'    au:alignsTo st:term-{slug(other)} ;\n'
            f'    au:promotedBy st:authoring .'
        )
    for term, why in sorted(retracted_terms.items()):
        lines.append(
            f'\nst:term-{slug(term)}\n'
            f'    au:demotedBy st:authoring ;\n'
            f'    rdfs:comment "not a term: {esc(why or "no reason given")}" .'
        )
    for subject, fields in sorted(amended.items()):
        body = [f'\nst:{subject}']
        if "text" in fields:
            body.append(f'    rfc:predicate "{esc(fields["text"])}" ;')
        if "modality" in fields:
            body.append(f'    rfc:modality rfc:{fields["modality"]} ;')
        if "discipline" in fields:
            body.append(f'    au:discipline st:{fields["discipline"]} ;')
        body.append('    au:promotedBy st:authoring .')
        lines.append("\n".join(body))
    for subject in sorted(retracted_ns):
        lines.append(
            f'\nst:{subject}\n'
            f'    au:demotedBy st:authoring ;\n'
            f'    au:stalledOn "withdrawn: an author proposed removing this requirement" .'
        )
    for subject, op in sorted(asserted.items()):
        lines.append(
            f'\nst:{subject} a rfc:NormativeStatement ;\n'
            f'    rfc:modality rfc:{op.get("modality", "MUST")} ;\n'
            f'    rfc:predicate "{esc(op.get("text", ""))}" ;\n'
            f'    rdfs:label "{esc(subject.upper())}" ;\n'
            f'    au:discipline st:{op.get("discipline", "unassigned")} ;\n'
            f'    au:rung au:R0 ;\n'
            f'    au:promotedBy st:authoring ;\n'
            f'    au:stalledOn "not-decomposed: newly written, nothing has broken it into terms yet" .'
        )

    out = pathlib.Path(args.corpus) / "proposals.ttl"
    text = "\n".join(lines) + "\n"

    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != text:
            print(
                f"STALE — {out} does not match {args.log}.\n"
                f"  Re-run without --check to promote the log into the corpus.",
                file=sys.stderr,
            )
            return 1
        print(f"up to date: {out}")
        return 0

    out.write_text(text)
    print(f"ops read:          {len(ops)}")
    print(f"terms bound:       {len(bound)}")
    print(f"terms aligned:     {len(aligned)}")
    print(f"terms retracted:   {len(retracted_terms)}")
    print(f"claims amended:    {len(amended)}")
    print(f"claims withdrawn:  {len(retracted_ns)}")
    print(f"claims written:    {len(asserted)}")
    print(f"-> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
